### ISSUE TITLE
Demo site at http://www.everystreetchallenge.com/ broken?

### ISSUE THREAD

**Issue by duncanharris** [matejker/everystreet#1]
After drawing polygon and then clicking "Generate Route" it shows "Loading..." above the search box and then nothing happens for a very long time:

![image](https://user-images.githubusercontent.com/8201825/95649662-8bd1e580-0ad6-11eb-94d6-e38896f101e1.png)

Also your link with text "The Grange, Edinburgh" to http://www.everystreetchallenge.com/route/fa462d3e-8c48-43ad-bfa1-06c4426f7328 on http://www.everystreetchallenge.com/about is broken too.

I am using Chrome Version 85.0.4183.121 (Official Build) (64-bit) on Ubuntu Linux.

**Comment by matejker** [comment]
Hi @duncanharris, 
I am sorry to hear that. Unfortunately, the backend of the page went down soon after Mark shared it on FB 😢

Now, it is back and working🤞 

If you experience any troubles, happy to take a look :)

**Comment by duncanharris** [comment]
I guess one obvious improvement would be some feedback for the poor user when server down, rather than an infinite pause :-)

**Comment by matejker** [comment]
> I guess one obvious improvement would be some feedback for the poor user when server down, rather than an infinite pause :-)

Good idea, I am pinging a health endpoint, in a case backend is down there will be a warning alert.
