### ISSUE TITLE
OpenStreetMap Licence

### ISSUE THREAD

**Issue by fredao** [matejker/everystreet#11]
I would be nice, if you could follow the OSM attribution rules

https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#How_should_I_attribute_you.3F

Thank you

**Comment by joostschouppe** [comment]
It's basic respect (as well as a legal obligation) to simply add "© [OpenStreetMap](https://www.openstreetmap.org/copyright) contributor" next to where you credit Leaflet.

**Comment by matejker** [comment]
@fredao and @joostschouppe thanks for reminding it, will fix it in following update!

**Comment by danieldegroot2** [comment]
> It's basic respect (as well as a legal obligation) to simply add "© [OpenStreetMap](https://www.openstreetmap.org/copyright) contributor" next to where you credit Leaflet.

It should be plural, "contributors" :-)
