### ISSUE TITLE
website version not working?

### ISSUE THREAD

**Issue by kyleormsby** [matejker/everystreet#15]
Excited to use this for some local projects but it appears the web app is not working. After clicking 'generate' I've been stuck on this loading screen for dozens of minutes:
![Screen Shot 2022-07-18 at 11 28 56 AM](https://user-images.githubusercontent.com/31013794/179578409-d9f9b0bc-50f7-45ec-a5ba-c5c2cd0c94da.png)

**Comment by afsscc** [comment]
Unfortunately, same here, irregardless of the area size I choose.

**Comment by bfontaine** [comment]
Same here, the `POST` on `https://lttapjswjh.execute-api.eu-west-1.amazonaws.com/v/route` fails with a 503.

**Comment by matejker** [comment]
Hi all,

Unfortunately, on of the API provides used in OSMnx, decreased its capacity and speed, so it is no longer able to spin up, download and run the algorithm within the _max possible time-out_ of AWS Lambda & API Gateway. I leave it for now, if the problem got resolve it in the same way it come - by itself. 

Possible solution could be to turn it back to a Flask / FastApi service, which would save some time as it doesn't require to spin up for every request.

I am open to any ideas at stage :)

**Comment by Peterhaydo** [comment]
I also have this problem and have tried the http://www.everystreetchallenge.com/ page on Edge, Chrome browsers as well as Safari on my iPhone, allw tih the same 'stuck on LOADING' result. I'd love to use this progam to help me walk every street in London, so is there a fix as yet?

**Comment by MeijeSibbel** [comment]
![image](https://user-images.githubusercontent.com/11735738/212547958-3a6f1bd7-c3b8-4d6e-88ad-be31bd42780f.png)

It appears that nothing is being generated @matejker

**Comment by Peterhaydo** [comment]
It's a shame this bug is not fixed as there appears to be no other solution to this problem on the internet and there are many people who would find it really useful.

**Comment by bfontaine** [comment]
@Peterhaydo @MeijeSibbel everything you have to know about this bug are in [matejker’s comment above](https://github.com/matejker/everystreet/issues/15#issuecomment-1225333165). Each comment notifies everyone in the thread, so I don’t think adding more comments to say it doesn’t work (we know!) or "it’s a shame" it’s not fixed are helpful. If this is important for you, why don’t you give it a try? Open-source is built on collaboration, after all.

**Comment by eyramm** [comment]
> Hi all,
> 
> I am really sorry for that 😭
> 
> Unfortunately, one of the API provides used in OSMnx, decreased its capacity and speed, so it is no longer able to spin up, download and run the algorithm within the _max possible time-out_ of AWS Lambda & API Gateway. I left it till now, if the problem got resolve it in the same way it come - by itself.
> 
> Possible solution could be to turn it back to a Flask / FastApi service, which would save some time as it doesn't require to spin up for every request.
> 
> I am open to any ideas at stage :)

Hello @matejker I'll like to host this project. Can we discuss this in detail? How do I reach out?
I am also trying to host this project locally. There are no instructions.

**Comment by kevinp2** [comment]
Hi, just confirming that this is still an issue and the website does not work as of Sept 16, 2023.

@matejker: it is possible to run this as a local Python file?  I am not really familiar with how Jupyter notebooks work.  Can I just assemble the Python code snippets into a single Python **.py** file?  I am familiar with OSMNx, but have only used it in local standalone Python files.

**Comment by matejker** [comment]
Hi all (@kevinp2, @eyramm, @bfontaine, @Peterhaydo, @MeijeSibbel , @kyleormsby)

The web service _should be_ back, however it is computationally expensive process and it requires data from an external API, for larger maps it could time out. But you can always try again or try to run it locally :)

**Comment by kevinp2** [comment]
> Hi all (@kevinp2, @eyramm, @bfontaine, @Peterhaydo, @MeijeSibbel , @kyleormsby)
> 
> The web service _should be_ back, however it is computationally expensive process and it requires data from an external API, for larger maps it could time out. But you can always try again or try to run it locally :)

Hi @matejker , do you have any instructions on how to run it locally easily?  I have a Python installation already.

**Comment by matejker** [comment]
Hi @kevinp2, 

Try https://github.com/matejker/everystreet?tab=readme-ov-file#usage

**Comment by kevinp2** [comment]
Hi @matejker ,

I think most of us are interested in the web app, not just the pure Python script.  In particular, **the ability to draw a polygon is most useful**.  I looked in the usage file and documents but could not find any info on how to get a copy of the web app set up locally.  Are you using Flask or some other framework?

This is how I use the web app:

<img width="681" alt="EveryStreet" src="https://github.com/matejker/everystreet/assets/609677/97599784-3013-47b8-8fe5-5fdd7a6fed76">

**Comment by matejker** [comment]
You can hack, if look at the request payload, you can see the polygon. Then you can get the underlying network using [osmnx.graph.graph_from_polygon](https://osmnx.readthedocs.io/en/stable/user-reference.html#osmnx.graph.graph_from_polygon)
![Screenshot 2024-02-07 at 18 15 32](https://github.com/matejker/everystreet/assets/45606539/3dc2dbf7-85e8-4862-9a5b-4d3a70fb4ec2)

then

**Comment by kevinp2** [comment]
@matejker :

after obtaining the polygon, how do you calculate the shortest path through all of the streets of the polygon?

**Comment by kevinp2** [comment]
FYI, as of Oct 29, 2024, the website is working for at least small neighborhoods.
