### ISSUE TITLE
requirement version conflicts

### ISSUE THREAD

**Issue by joefizz** [matejker/everystreet#25]
What you've created here looks awesome but as others have found the web app doesn't work.  I've tried to clone and setup locally but the requirements are conflicting.  I modded the version requirements for a while to try and fix it, then ended up just removing all version specifications but it still doesn't work.  The worst of it is:

```
The conflict is caused by:
    The user requested networkx
    osmnx 1.2.2 depends on networkx>=2.8
    mk-network 0.1.1 depends on networkx==2.4
```

**Comment by matejker** [comment]
Hi @joefizz,

Thanks for reaching out. Yeah there seemed to be a dependency conflict, I have now updated [pyproject.toml](https://github.com/matejker/everystreet/blob/master/pyproject.toml) and migrate the network package to [Poetry](https://python-poetry.org/). 

Cheers! 

Matej
