### ISSUE TITLE
fatal: unable to connect to github.com

### ISSUE THREAD

**Issue by Sasni** [matejker/everystreet#30]
I'm sorry, is it a local problem or is it not possible to install in general?
Should I do something?
```
 pip install -e git://github.com/matejker/network@master#egg=network

Obtaining network from git+git://github.com/matejker/network@master#egg=network
  Cloning git://github.com/matejker/network (to revision master) to c:\laragon\www\pyt\everystreet-master\src\network
  Running command git clone --filter=blob:none --quiet git://github.com/matejker/network 'C:\laragon\www\PYT\everystreet-master\src\network'
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.4]: errno=Unknown error

  error: subprocess-exited-with-error
```

**Comment by MarkusWo** [comment]
I have the same problem. I think it has to do with being behind a firewall. If I run `git clone https://github.com/matejker/network` it works fine. I just don't know how to tell pip to always use an https connection, so in the end I still am not able to get this running as intended.

**Comment by ctrlaltf2** [comment]
I was able to fix this using:
```bash
pip install -e git+https://github.com/matejker/network@master#egg=mk-network
```
where master as of right now is at `05a9608`. The protocol being `git+https` fixed my connection issue, and `egg=mk-network` solved the followup issue about some kind of naming conflict.
